image: php:8.0.2
before_script:
  - apt-get update -qq
  - apt-get install -y -qq git

deploy to heroku:
  stage: deploy
  image: ruby:2.6
  script:
    - gem install dpl --version 1.10.15
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - main
